### ISSUE TITLE
Integer fields not accepted as weight values

### ISSUE THREAD

**Issue by Nate-Wessel** [havatv/qgisstandarddeviationalellipseplugin#9] opened 2018-09-23 15:59 UTC
I've encountered an issue where integer fields (in this case from a shapefile) do not show up as an option in the weights dropdown menu. If I calculate a new field and set the type as real it will show up in the menu.

**Comment by havatv** [comment] 2018-09-23 19:28
Thank you for reporting @Nate-Wessel.  I will have a look, but it could be useful to know if the issue is with QGIS 2 or QGIS 3 (or both).

**Comment by Nate-Wessel** [comment] 2018-09-23 19:38
I can't recall which version we originally found the problem on; my students ran into the error working on some lab computers. I was able to reproduce it just now on my laptop though running version 3.2.

I also noticed that this was not an issue for integer fields from PostGIS.
(edited to correct QGIS version)

**Comment by havatv** [comment] 2018-09-23 20:49
Never mind.  I found the reason for the issue, and a fix for QGIS 3.  I will upload a new version soon.  Thanks again!

**Comment by havatv** [comment] 2018-09-24 06:25
The issue should be fixed in version 1.2.3 (QGIS 2) and 3.0.3 (QGIS 3), that have now been uploaded to plugins.qgis.org.  Closing the issue.  Please re-open if the problem persists.

**Closed as completed by havatv** 2018-09-24 06:25 UTC
Labels: bug

**Comment by Nate-Wessel** [comment] 2018-09-24 17:11
Thanks for the quick response!
